#include "platform.h"

#ifdef LINUX
#include "linux/opengl/opengl.cpp"
#include "linux/opengl/opengl.h"
#include "linux/opengl/shader.cpp"
#include "linux/opengl/shader.h"
#include "linux/opengl/vao.cpp"
#include "linux/opengl/vao.h"
#include "linux/opengl/vbo.cpp"
#include "linux/opengl/vbo.h"
#include "linux/thread/thread_linux.cpp"
#include "linux/thread/thread_linux.h"
#include "linux/utils/utils_linux.cpp"
#include "linux/utils/utils_linux.h"
#include "linux/window/window_linux.cpp"
#include "linux/window/window_linux.h"
#else
#include "win_32/window/window_win32.h"
#include "win_32/window/window_win32.cpp"
#include "win_32/utils/utils_win32.h"
#include "win_32/utils/utils_win32.cpp"
#include "win_32/thread/thread_win32.h"
#include "win_32/thread/thread_win32.cpp"
#include "win_32/opengl/opengl.cpp"
#include "win_32/opengl/shader.cpp"
#include "win_32/opengl/vao.cpp"
#include "win_32/opengl/vbo.cpp"
#endif
